name: Docs CI

on:
    push:
        branches: [ master ]
        paths-ignore:
            - .vscode
            - .husky
            - .github
            - '!.github/workflows/build.yml'
    pull_request:
        paths-ignore:
            - .vscode
            - .husky
            - .github
            - '!.github/workflows/build.yml'
    workflow_dispatch:
        inputs:
            checked:
                type: boolean
                description: 'Docs have been checked.'
                default: false
                required: false

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
    check:
        name: Check docs site
        if: ${{ github.event_name != 'workflow_dispatch' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Cache deps & types
              uses: actions/cache@v4
              with:
                key: neuropilot-docs-${{ github.repository }}
                path: |
                    .astro

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                version: 10.14.0
            
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 22.14.0
                cache: 'pnpm'
                cache-dependency-path: "./pnpm-lock.yaml"
            
            - name: Install deps
              run: |
                pnpm install --frozen-lockfile
            
            - name: Run basic checker
              run: pnpm check
    build:
        name: Build docs site
        if: ${{ github.event_name != 'pull_request' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Cache deps, types, output
              uses: actions/cache@v4
              with:
                key: neuropilot-docs-${{ github.repository }}
                path: |
                    .astro
                    .cache
                    dist
            
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                version: 10.14.0
            
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 22.14.0
                cache: 'pnpm'
                cache-dependency-path: "./pnpm-lock.yaml"
            
            - name: Setup Pages
              id: pages
              uses: actions/configure-pages@v5
            
            - name: Install deps
              run: |
                pnpm install --frozen-lockfile

            - name: Build site
              run: |
                if [ "${{ github.event_name }}" = "push" ]; then
                  export PUBLIC_NEXT=true
                elif [ "${{ inputs.checked }}" = "false" ]; then
                  export PUBLIC_NEXT=true
                fi
                PUBLIC_VERSION=$(npm show ./ version) pnpm build
            
            - name: Upload GitHub Pages Artifact
              uses: actions/upload-pages-artifact@2d163be3ddce01512f3eea7ac5b7023b5d643ce1 # Pinning to SHA because that thing hasn't updated in a year it seems
              with:
                path: ./dist
    deploy:
        name: Deploy to GitHub Pages
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy -> GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
