name: Bump docs version

permissions:
    contents: write

on:
    workflow_dispatch:
        inputs:
            version:
                type: choice
                description: 'Bump docs version by how much?'
                required: true
                default: 'none'
                options:
                    - 'major'
                    - 'minor'
                    - 'patch'
                    - 'none'
            check:
                type: boolean
                description: 'Docs have been checked.'
                required: true
                default: false

jobs:
    bump:
        name: Bump docs version
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                version: 10.14.0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 'latest'
                cache: 'pnpm'
                cache-dependency-path: './pnpm-lock.yaml'

            - name: Install deps
              run: pnpm install --frozen-lockfile

            - name: Configure git
              run: |
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"

            - name: Bump version
              run: |
                pnpm version ${{ inputs.version }}
                git push --follow-tags
            
            - name: Call workflow
              run: gh workflow run build.yml -f checked=true